### PR TITLE
Variable frame rate

### PR DESCRIPTION
**Pull request by BrianMcRails**
Added RecommendedDisplayFrameRate tag to the image meta, and use it when playing a multiframe image. If the value is not present but image is playing it will default to 10fps.

### CODE REVIEW

**Comment by BrianMcRails** [comment]
#476

**Comment by BrianMcRails** [comment]
Putting on hold until I get QUnit and tests working.

**Comment by ivmartel** [comment]
QUnit and PhantomJs can be a pain sometimes... and difficult to debug... I'll try to give it a look too.

**Comment by ivmartel** [comment]
I created an issue for the coverage (#479). It can be fixed later so I can merge your pull request now, is it OK with you?

**Comment by ivmartel** [comment]
Thanks for the PR @BrianMcRails !

**Pull request merged**
