### PR TITLE
implemented queue for loadUrls

### PR DESCRIPTION
**Pull request by rawl05**
Implemented queue for LoadUrls. The browser used to hang when loaded with series having more than 500 files to the loader.

### CODE REVIEW

**Comment by ivmartel** [comment]
I guess this PR replaces #722. Can you close the other one please? 

This PR is more concise than the other one, thanks for your work!

**Comment by rawl05** [comment]
Added check for requests in queue so that when aborted only requests already in queue are cancelled, earlier requests not queue also used to get queued and get cancelled which used to hang the browser.

**Comment by ivmartel** [comment]
Thanks for you work. Instead of filtering the `finalUrlArray`, you could just remove the launched request when you in the `triggerNextReq`. 

And does this code fix your issue of too many requests at the same time?

**Comment by rawl05** [comment]
Launching new request in triggerNextReq help queue another request which hasn't been triggered yet. I've implemented this in my minor project and queuing worka just perfect. The browser is also stable. finalUrlArray hold various flags regarding individual request which helps in queuing. I don't have strong hand on JavaScript, I'm working on Angular 8, if you could optimize my code would be great.

Also, second commit contains logic to cancel only requests that are in queue, earlier requests not in queue used to get queued and then get cancelled. This helps if series has more than 1000 images. Tested both of these for series with around 4500 images.

**Comment by ivmartel** [comment]
Checkout what I did on the [730-load-url-queue](https://github.com/ivmartel/dwv/tree/730-load-url-queue) branch, it should be similar to this.

**Comment by rawl05** [comment]
Went through the code. Are you queuing one request at a time?

**Comment by ivmartel** [comment]
No, the effect is the same as your code, it launches n requests at the same time and whenever one finished, it launches the next one in the list.
The size of the initial batch is set in the options object. I need to allow passing it to the `application.loadURLs` method.

**Comment by rawl05** [comment]
Okay. Thank you. Allowing it to be passed from `application.loadURLs` would be great.

**Comment by ivmartel** [comment]
Ok, done in 6636390.

**Comment by arturojain** [comment]
I hardcoded this in v0.27.0 and it only loads the first queue not triggering `triggerNextReq`. Am I missing something?

**Comment by ivmartel** [comment]
I think the code of the pull request works but better to try the one of the [730-load-url-queue](https://github.com/ivmartel/dwv/compare/730-load-url-queue) branch since it is the one that allows to set the batch size from the `app.loadURLs`.

**Comment by arturojain** [comment]
Transitioned to [730-load-url-queue](https://github.com/ivmartel/dwv/compare/730-load-url-queue). 

I still can't solve the hanging and crash problem on iOS on series with 500+ files. Tried to implement some kind of pagination but keep getting error `Error: The first object already contains id2: XXX, id1: XXX, YYY, ZZZ`. **Any ideas why this error is showing or how to "clear" old data in order to avoid merge?**

**Comment by ivmartel** [comment]
This error happens when merging files meta data and the merged object already contains the info to merge, as if you were loading slices twice, is it possible?

**Comment by ivmartel** [comment]
@arturojain #738 is fixed, the problem was in the data decoding.

The work on [730-load-url-queue](https://github.com/ivmartel/dwv/compare/730-load-url-queue) is valid, I created PR #780 to integrate it. It replaces this PR.

**Pull request closed without merging**
