### PR TITLE
io/file.js

### PR DESCRIPTION
**Pull request by rafasoyyo**

### CODE REVIEW

**Comment by ivmartel** [comment]
To understand well, instead of loading multiple files in parallel with the for loop, you load files sequentially. That way you avoid allocating too much memory at the same time but the code is a bit slower. What do you use to check the peak memory consumption, the Google Chrome Profiles for heap allocations and the peak values? 

Your comment says: `this way increase time needed to load images but reduce FileReader memory consume. Also improve progressive image display.  tested in Chrome width 500Dicom, 600kb each, time increase ~400ms and memory decrease ~200Mg`. You get one of these "Aw snap" page without this change?

Not sure if the code could adapt to the maximum memory available, is there such a value available from the browser?

**Comment by rafasoyyo** [comment]
If you try lo load a small amount of images, reading in parallel work fine! but when you try to load medium or big sequences, sequencial reading works better. A simply watching to google task show the issue. I have done some audits with Chrome and firefox developers tools and that is the first piece of code I have found to reduce the consumes of memory, comparing only the reading in both ways. Now I am searching for more points because this doesn't resolve the memory leak completely.

As far as I know, only Chrome has a command to acces to something related with the memory "window.performance.memory" (https://developer.mozilla.org/es/docs/Web/API/Window/performance) but even with this info I can not imagine how to make de process depending on memory usage.

**Comment by ivmartel** [comment]
I have found a SO post that goes your way: [filereader-reading-many-files-with-javascript-without-memory-leaks](http://stackoverflow.com/questions/30767835/filereader-reading-many-files-with-javascript-without-memory-leaks). The answer says:  

> It seems that browsers expect you to reuse FileReaders.

(it would be good to have a reference for this affirmation)

**Comment by rafasoyyo** [comment]
After last release, I think this PR has no sense. I have not check if FileReader reuse has important impact on memory but I don't think it has. Close it if you consider this PR useless!

**Comment by ivmartel** [comment]
Sorry I did not have more time to investigate this. Closing...

**Pull request closed without merging**
