### PR TITLE
Delete all draws from all layers

### PR DESCRIPTION
**Pull request by rafasoyyo**
maybe this is not the best place to include this function but I have not found a better one :(

### CODE REVIEW

**Comment by ivmartel** [comment]
This could be added to the app class. I need to think of a refactor to group draw functionality together.

**Comment by ivmartel** [comment]
I added the method to the app class, see a09609b. Good enough to close this PR?

**Comment by ivmartel** [comment]
I forgot to mention that I changed the setting of the 'name' string used with the delete command. I also changed the name of the method.

**Comment by rafasoyyo** [comment]
That's perfect for me, but anyway, it should be good enought for you ;D

I wonder if you prefer to receive PR from me or maybe just open issues or other methods...or maybe you prefer me to keep my hands far away fom your code...

Anaway, I suggest you to have a look to this library, could be usefull for big images:
https://github.com/nodeca/pica

**Comment by ivmartel** [comment]
Thanks for your contribution and please continue keeping your hands dirty with the dwv code!
PR is the preferred method to propose code changes.

**Pull request closed without merging**
