### PR TITLE
remove total slice buffer and reuse buffer from loader

### PR DESCRIPTION
**Pull request by frickt**
for performane reason
this commit obsoletes #548 and #558

### CODE REVIEW

**Comment by ivmartel** [comment]
Thanks for your work! My problem is that you seem to have removed the frame extra dimension, If I understand your code, you consider the first dimension to be either frame or slice. The buffer is supposed to be an array of arrays, the first dimension being the frame and then the slice. The idea is to support data as the one provided in #493.

**Comment by frickt** [comment]
hm... I see, didn't know that.
So should we use 3 dimensions [frameIndex][sliceIndex][buffer]?

**Comment by ivmartel** [comment]
At the moment, there are just 2: `[frameIndex][buffer]`. Adding a third one could help to have an easier append slice like you do in this PR and avoid the copy.

**Comment by frickt** [comment]
ok, i rewrote it to use 3d buffer.

**Comment by ivmartel** [comment]
Looking good! So how does it compare to the current version of the code? Storing the 3D data in a huge 1d array is kind of old fashion, I'm not sure there is a real benefit compared to this array of array solution.

**Comment by frickt** [comment]
is there somethink i need to change get this merged?

**Comment by ivmartel** [comment]
No, looking good, I was just finishing the 0.24.1patch release.

**Comment by ivmartel** [comment]
And now, I'm reviving the [dcmbench](https://github.com/ivmartel/dcmbench) project to evaluate your changes, I'm nearly there...

**Comment by ivmartel** [comment]
Looking good on the default demo data of [dcmbench](https://github.com/ivmartel/dcmbench), will integrate soon.

**Comment by ivmartel** [comment]
I know its an old one, but I need more time to investigate...

**Comment by ivmartel** [comment]
Closing for now, follow #905 for new strategy.

**Pull request closed without merging**
