### PR TITLE
Show DICOM headers and patient orientations to Info layers.

### PR DESCRIPTION
**Pull request by tmskmr**
Hi, thank you very much for your helpfull software.
I have implemented the functionality to show DICOM headers and patient orientations to header<xx> div if they exist in the HTML file. (<xx> is a two-letters to specify which of the four corners and the four edges of the image window, such as "tl" for the top left.) , The set of the DICOM tags, their order, prefix, and suffix can be configured in the "resources/headers.json" file per modality.
Could you consider to merge this code to your repository if you think it useful?
Let me know if you have any questions.

### CODE REVIEW

**Comment by ivmartel** [comment]
Thanks @tmskmr! This looks very interesting! I would be happy to merge it once it passes its checks, the main problem for now being linting, see the build [log#L312](https://travis-ci.org/ivmartel/dwv/builds/234273851#L312). 

It seems you kept the old 'info' objects alive, you can remove them, your code seems like a good replacement. And also, I am not too sure about the naming ('headers'), I would prefer 'info' or something more meaningful, 'overInfo' maybe...

**Comment by tmskmr** [comment]
Thank you for your suggestions. I would like to correct my code as follows:
1. remove the old 'info' objects and rename 'header' to 'info'.
2. solve the linting check failure. (Sorry, I am almost beginner at JavaScript.)
Should I create another pull request or may I just commit the above? (I am also beginner at github.)

**Comment by ivmartel** [comment]
Perfect!

If you commit changes to your `custom-overlay` branch, they will get added here too (cf [about-pull-requests](https://help.github.com/articles/about-pull-requests/)).

**Comment by ivmartel** [comment]
Thanks @tmskmr for your latest commit. The linting is still not passing (cf travis build [1098#L322](https://travis-ci.org/ivmartel/dwv/builds/236229405#L322)). From what I get, you can leave the event one commented out (surround it with `/*` and `*/`) and remove the image one since it does not seem to be used.

**Comment by tmskmr** [comment]
Thanks @ivmartel for your suggestions. I fixed the lint errors, but travis-ci test seems to failed. I don't  know why.

**Comment by ivmartel** [comment]
The problem is with the `image.overlays`. The test tries to append a slice to an image. The image class can be used without a view, so the array initialisation you are doing (`image.overlays = [];`) in the view class should be done in the image class. You can add a member at the top, for example after the histogram (`var histogram = null;`), it should look like: `var overlays = [];`. Then, before you splice in the `image.append`, it would be best to check that the overlays are not empty, both for `this` and for `rhs`.

**Comment by ivmartel** [comment]
In the images class, you do not need to use `this` to use the `overlays` array.

**Comment by tmskmr** [comment]
Thanks. I fixed it, and another error is now reported. Should I change  `@return {String Array}` to `@return {Array}` or something?

**Comment by ivmartel** [comment]
Yes, `@return {Array}` should work!

**Pull request merged**
