### PR TITLE
bug fixed

### PR DESCRIPTION
**Pull request by gaopeng0108**
if we choose a .jpg or .png firstly, and then we choose a dicom file,  the code will report an error

### CODE REVIEW

**Comment by ivmartel** [comment]
Hi @gaopeng0108, thanks for the pull request but I cannot reproduce the bug you describe. Which browser are you using? Are you loading files or via links?

**Comment by gaopeng0108** [comment]
I'm using the latest chrome，i have tested the url (https://ivmartel.github.io/dwv/demo/stable/viewers/static/index.html) that you provide just now。
first，you can choose a jpg file，the next step is to choose a .dcm file in the same window， you will get error that TypeError: Cannot read property 'hasChildNodes' of undefined.

**Comment by ivmartel** [comment]
I still cannot reproduce. I'm using the static viewer of the stable demo you mention.
I load a jpg file then a dicom one in the same window either via drag and drop or using the 'Browse' button and I do not get an error. There must be something I'm missing...

**Comment by gaopeng0108** [comment]
like this，animation

**Comment by ivmartel** [comment]
Thanks for the gif, now I get it! You are getting this error because the localised version of the 'overlays.json' file is missing a section for DOM files. Since this can happen, I'll integrate your changes and fix the overlays configuration file.

**Pull request merged**
