### PR TITLE
adding a banner and a footer to grunt concat task to make dwv usable …

### PR DESCRIPTION
**Pull request by yulia-tue**
…in node require function

### CODE REVIEW

**Comment by ivmartel** [comment]
I'm new to modules, I guess you want to do the same this page describes: [writing-javascript-modules-for-both-browser-and-node](http://www.matteoagosti.com/blog/2013/02/24/writing-javascript-modules-for-both-browser-and-node/)

I tried loading the mobile viewer with your changes from the browser, but I get a `Uncaught TypeError: i18next.use is not a function` error (called from the `applauncher.js`). 

Is there a specific way to load/call dependencies?

**Comment by yulia-tue** [comment]
Hi, sorry for taking so long to answer. 
I think, I haven't put i18next as a global. The header and the footer basically create a closure, so you only export objects you specify, and everything else that is initialized inside the closure is not accessible from the outside. 
Is there any other globals that you use, accept dwv and i18next? I found these: 
- dwv
- Kinetic
- JpegImage
- jpeg
- JpxImage
- MagicWand
- i18next
- i18nextXHRBackend
- i18nextBrowserLanguageDetector

I will have a look at how the external dependency are handled in this setup, since if I understand correctly, some of these globals are not directly initialized in the dwv code, but rather declared as external libs.

**Comment by ivmartel** [comment]
Your list seems complete! Thanks for your help.

**Comment by ivmartel** [comment]
I think I fixed this one in 12cfd2b. I'm using the [umdjs](https://github.com/umdjs/umd) design. Since it's a few lines of code, I created specific files for the [intro](https://github.com/ivmartel/dwv/blob/master/resources/module/intro.js) and [outro](https://github.com/ivmartel/dwv/blob/master/resources/module/outtro.js). They are concatenated in order in the 'src' option of the grunt concat task.
I'm using the minimal dependencies, I still have to think about the other ones...

I just tried it in the browser, still have to test with node and bower...

**Comment by ivmartel** [comment]
Should all be good, at least for the minimal dependencies, in release 0.19.0...

**Pull request closed without merging**
