### PR TITLE
Drawings and states using groups

### PR DESCRIPTION
**Pull request by rafasoyyo**
- Manage position-group creation dynamically.
- Add drawings, floodfills and livewires to corresponding position-groups.
- dbl-click event of LIvewire tool behavior improved.
- Undo and Redo is still working.
- Drawings table is still working.
- Save "states.json" using objects instead of arrays to identify elements unequivocally and avoid creation of empty elements to mantein order.
- Backward compatibility maintained reading and drawing "state.json".
- Minor error fixed(editor.js).

### CODE REVIEW

**Comment by ivmartel** [comment]
Thanks for all this @rafasoyyo! 

Just about the state, I quite like relying on Konva to stringify and parse its objects instead of looping on objects ourselves. It simplifies the code and makes it more maintainable. Regarding v0.2 support, I was thinking of recreating the stage from the JSON and then pass it to the app. What do you think?

**Comment by rafasoyyo** [comment]
Hi @ivmartel!
I tried different ways and this is the most simple, maintainable and less verbose code way I have found.

Some of the considerations I have done is that:
 - It avoids saving unnecesary info (empty arrays)
 - It allows the identification of the information unequivocally independently of the position in the saved state and reducing loops on loading.
 - The number of lines is reduced in global.

Anyway, let me check and try it again.

Thanks for your comments!

**Comment by ivmartel** [comment]
I created the branch https://github.com/ivmartel/dwv/tree/442-less-canvas-b1 to show what I meant. 

Looking at this pointed out the problem of loading a state on a canvas that does not have the same size as the one when the state was created... I'm looking into this...

**Comment by ivmartel** [comment]
Saving the layer in the state and not the full stage fixes the size problem. I updated the new branch.

**Comment by rafasoyyo** [comment]
I have merge your code to manage states and my code to manage groups drawings and seems to work fine.

I am not sure if you have shared this code as a example or it is they way you would like it will be...
I am working to support also v01 drawings but I am not sure what is the best version to do it, right now I am working with v0.11.

 I have realized that that [dwv.DrawController.getCurrentDrawLayer](https://github.com/ivmartel/dwv/blob/442-less-canvas-b1/src/app/drawController.js#L92)  and [dwv.DrawController.getDraws](https://github.com/ivmartel/dwv/blob/442-less-canvas-b1/src/app/drawController.js#L92) do the same. Maybe it is possible to use getCurrentDrawLayer in the state feature and change getDraws to return an array or drawings(Konva group of shapes) but I would like to know your opinion.

**Comment by ivmartel** [comment]
The `442-less-canvas-b1` branch was to show my ideas. If it is ok with you, I'll merge it back into `442-less-canvas`.  My next step is to change the state methods to enable automatic testing. Once this is done, we can add state v0.1 testing too. I'm ok with using dwv v0.11 as reference.

I'm ok with using `getCurrentDrawLayer` in the state. But I'm not sure what you want to use the new `getDraws` method for?

**Comment by ivmartel** [comment]
About using dwv v0.11 as reference for state v0.1, that does not fit with what I see in the history. The version got added at commit dfd1b7f which then got released as dwv v0.15. There was no version before. 

I'm done with simple shape tests for v0.2 and v0.3. I try to keep the same shapes between versions to simplify the tests, I'll carry on with v0.1. The state format with no version is very basic, I do not think it is worth still supporting it, isn't it?

I added the state format history in the doc of the state class: [state.js#L10](https://github.com/ivmartel/dwv/blob/442-less-canvas/src/app/state.js#L10).

**Comment by rafasoyyo** [comment]
Thanks @ivmartel.

I have made a few changes to manage states.json from v1 and v2 versions taking in account your considerations. All states versions has all features when are loaded.

I also think that unversioned states.json are out of scope.

Let me know if you have more considerations.

**Comment by ivmartel** [comment]
You seem to have removed the split I did in the state code. I created the apply method in order to test the state code on its own by just calling `fromJSON` without the app, see [tests/state/state.test.js#L33](https://github.com/ivmartel/dwv/blob/442-less-canvas/tests/state/state.test.js#L33). 

In order to make the tests work for v0.2, I had to add `draggable` to the read group in the `v02Tov03Drawings` method, otherwise once reloaded, only the `shape` gets dragged if you move the drawing.

I also return the layer `toObject` when serializing (and in the v0.2 conversion), in order to save the drawings as JSON and not as a string which seems to be the case when you just return the layer. 

I'll create some v0.1 test files and merge your v0.1 conversion. Don't hesitate if you have comments on the tests.

**Comment by rafasoyyo** [comment]
ok sorry, I'll check it!

**Comment by ivmartel** [comment]
I added the v0.1 state test data and also added multi slice state test data. This allowed to find missing parts to the update which are now fixed.

I'm using a different strategy to update v0.1 states: I do not touch the shape (too much and apart for the line) and mainly update the text to become a label. Using the factories is nice, but I am afraid of code change that would mean states are interpreted differently.

Your pull request introduces other changes that are interesting, we can discuss them after you merge 442-less-canvas into it.

**Comment by rafasoyyo** [comment]
The main reason of my strategy is that I thought that loads states.json from version 1 should not only load the data but update them to have all the new features available. I think that my approach is a little bit aggresive but it update drawings deeply so, for example, text.quant is added correctly, labels are like {surface} or {length} and some other improvements. 

I first tried to add the needed information to the loaded state.josn v1, but I realized that I was redoing what factories do so I thought, why not use factories directly.

what do  you think?

**Comment by ivmartel** [comment]
Your solution makes sense and works fine, it's just the dependencies it has (on the factories and therefore the app and the image) which make it difficult to automatically test. If you can update the new state tests with your solution I'd be happy to have a look at it!

It is true the current solution (on the branch) does not handle well the quantification, but since v0.15 did not allow to edit the text, I can replace the text with the appropriate 'flag' (for example `{length}` for the ruler).

**Comment by ivmartel** [comment]
Ok, I think the `422-less-canvas` branch is ready to be merged. I included (and adapted) most of your changes. I'll check later the typo in the `editor.js` and the changes you made to the livewire that do not seem related to the less canvas. Tell me if you have any concerns, otherwise I'll merge this weekend.

**Comment by ivmartel** [comment]
`442-less-canvas` was merged at #456. Closing this one.

**Pull request closed without merging**
